Class {
	#name : #ObjectReceivingAnnouncement,
	#superclass : #Object,
	#category : #'ACD-Tests'
}

{ #category : #'as yet unclassified' }
ObjectReceivingAnnouncement >> doAction1 [
	^ self
]

{ #category : #'as yet unclassified' }
ObjectReceivingAnnouncement >> doAction2 [
	^ 1 + 1 +2+3
]

{ #category : #'as yet unclassified' }
ObjectReceivingAnnouncement >> doSomething [
	1 + 4+3
]

{ #category : #'as yet unclassified' }
ObjectReceivingAnnouncement >> doSomethingElse [
	^ 1+ 2+ 3+ 4
]
